sudo: required

language: generic

services:
  - docker

before_install:
  - echo "start creating an image with dockerfile"
  - cd docker-react-app/
  - docker build -t dd1331/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dd1331/docker-react npm run test -- --coverage

after_success:
  - echo "test succeed!"

deploy:
  provider: elasticbeanstalk
  region: "ap-northeast-2"
  app: "docker-react-app"
  env: "Dockerreactapp-env"
  bucket_name: "elasticbeanstalk-ap-northeast-2-145358528946"
  bucket_path: "docker-react-app"
  on:
    branch: master
    
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_ACCESS_KEY