sudo: required

language: generic

services:
	- docker

before_install:
	- echo "start creating an image with dockerfile"
	- docker build -t charlie/docker-react -f Dockerfile.dev ./docker-react-app/

script:
	- docker run -e CI=true charlie/docker-react npm run test -- --coverage

after_success:
	- echo "test succeed!"