sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t dd1331/docker-frontend-test -f ./docker-frontend/Dockerfile.dev ./docker-frontend

script:
  - docker run -e CI=true dd1331/docker-frontend-test npm run test -- --coverage

after_success:
  - echo "test succeed!"
  - docker build -t dd1331/docker-frontend ./docker-frontend
  - docker build -t dd1331/docker-backend ./docker-backend
  - docker build -t dd1331/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" --password-stdin

  - docker push dd1331/docker-frontend
  - docker push dd1331/docker-backend
  - docker push dd1331/docker-nginx