sudo: required

language: generic

services:
  - docker

before_install:
  - docker build -t charlie/docker-frontend-test -f ./docker-frontend/Dockerfile.dev ./docker-frontend

script:
  - docker run -e CI=true charlie/docker-frontend-test npm run test -- --coverage

after_success:
  - echo "test succeed!"
  - docker build -t charlie/docker-frontend ./docker.frontend
  - docker build -t charlie/docker-backend ./docker-backend
  - docker build -t charlie/docker-nginx ./nginx

  - echo "$DOCKER_HUB_PASSWORD" | docker login -u "$DOCKER_HUB_ID" -password-stdin

  - docker push charlie/docker-frontend
  - docker push charlie/docker-backend
  - docker push charlie/docker-nginx