FROM node:alpine

WORKDIR /usr/src/app

COPY package.json ./

RUN npm install

COPY ./ ./

CMD [ "npm", "run", "start" ]

# 개발용 도커파일명 명시 
# docker build -f Dockerfile.dev ./

# 컨테이너 내부에서 테스트 실행
# docker run -it dd1331/docker-react npm run test